%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Diagnostics Fixed Effects
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%1) Call R-script to run diagnostics
RPath='C:\Program Files\R\R-3.4.2\bin\x64';
RPath2=strcat('"',RPath,'"');
callname= strcat({RPath2},{'\'},{'R CMD BATCH '},{'"'},pwd,'\Diagnostics.R',{'"'});
Rcallname=callname{1};
system(Rcallname)



% 2) Load diagnostics file generated by the R script and
% Metropolis_Hastings rejction probabilities for theta

load('ResultsDiag_FixedEffects.mat')
load('ResultsDiag_Theta.mat')
fileID = strcat('eye_filtered_wave_fmm\eye_filtered_wave_fmm_Results_0_newtheta.dat');
fid = fopen(fileID);
A = fread(fid,inf,'*double');
fclose(fid)



% 4) Remove age from the fixed effects
K=size(Geweke_beta_basis,1)/4;
T=14400;
Age_index=2; %3 for model 8
index_basisspace=(Age_index-1)*K+1:1:Age_index*K;

EffectiveSize_beta_basis(index_basisspace')=[];
Geweke_beta_basis(index_basisspace')=[];

%5) Compute % of rejections and p-values

Rejections_beta_basis=sum(abs(Geweke_beta_basis)>1.96)/size(Geweke_beta_basis,1);
PValue_beta_basis=2*(1-normcdf(abs(Geweke_beta_basis)));
Rejections_nonparametric_basis=sum(abs(Geweke_nonparametric_basis)>1.96)/size(Geweke_nonparametric_basis,1);
PValue_nonparametric_basis=2*(1-normcdf(abs(Geweke_nonparametric_basis)));
Rejections_thetabasis=sum(abs(Geweke_thetabasis)>1.96)/size(Geweke_thetabasis,1);
PValue_thetabasis=2*(1-normcdf(abs(Geweke_thetabasis)));

% 6) Compute MH acceptance probability
 
B=1000;
MCMC_newtheta = reshape(A,K,B);
Acceptance=1-mean(MCMC_newtheta,2);

MeanA=nanmean(Acceptance);
QuantilesA=quantile(Acceptance,[0.025 0.05 0.5 0.95 0.975]);

MH_AcceptanceProbabilities=[MeanA';QuantilesA'];

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Summaries
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

MeanPV0=nanmean(PValue_beta_basis);
QuantilesPV0=quantile(PValue_beta_basis,[0.025 0.05 0.5 0.95 0.975]);
indInf=find(Geweke_beta_basis==-Inf | Geweke_beta_basis==Inf);
Geweke_beta_basis(indInf)=[];
MeanGEW0=nanmean(Geweke_beta_basis);
QuantilesGEW0=quantile(Geweke_beta_basis,[0.025 0.05 0.5 0.95 0.975]);
MedianESS0=median(EffectiveSize_beta_basis);


MeanPV3=nanmean(PValue_nonparametric_basis);
QuantilesPV3=quantile(PValue_nonparametric_basis,[0.025 0.05 0.5 0.95 0.975]);
indInf=find(Geweke_nonparametric_basis==-Inf | Geweke_nonparametric_basis==Inf);
Geweke_nonparametric_basis(indInf)=[];
MeanGEW3=nanmean(Geweke_nonparametric_basis);
QuantilesGEW3=quantile(Geweke_nonparametric_basis,[0.025 0.05 0.5 0.95 0.975]);
MedianESS3=median(EffectiveSize_nonparametric_basis);


MeanPV4=nanmean(PValue_thetabasis);
QuantilesPV4=quantile(PValue_thetabasis,[0.025 0.05 0.5 0.95 0.975]);
indInf=find(Geweke_thetabasis==-Inf | Geweke_thetabasis==Inf);
Geweke_thetabasis(indInf)=[];
MeanGEW4=nanmean(Geweke_thetabasis);
QuantilesGEW4=quantile(Geweke_thetabasis,[0.025 0.05 0.5 0.95 0.975]);
MedianESS4=median(EffectiveSize_thetabasis);



%Combined Basis Space
PValue_combined_basis=[PValue_beta_basis;PValue_nonparametric_basis;PValue_thetabasis];
Geweke_combined_basis=[Geweke_beta_basis;Geweke_nonparametric_basis;Geweke_thetabasis];
Effectivesize_combined_basis=[EffectiveSize_beta_basis;EffectiveSize_nonparametric_basis;EffectiveSize_thetabasis];


MeanPV6=nanmean(PValue_combined_basis);
QuantilesPV6=quantile(PValue_combined_basis,[0.025 0.05 0.5 0.95 0.975]);
indInf=find(Geweke_combined_basis==-Inf | Geweke_combined_basis==Inf);
Geweke_combined_basis(indInf)=[];
MeanGEW6=nanmean(Geweke_combined_basis);
QuantilesGEW6=quantile(Geweke_combined_basis,[0.025 0.05 0.5 0.95 0.975]);
MedianESS6=median(Effectivesize_combined_basis);

Rejections_combined_basis=sum(abs(Geweke_combined_basis)>1.96)/size(Geweke_combined_basis,1);



% Generate Table

Aux0=[MeanPV0';QuantilesPV0';MeanGEW0';QuantilesGEW0';MedianESS0';Rejections_beta_basis];
Aux3=[MeanPV3';QuantilesPV3';MeanGEW3';QuantilesGEW3';MedianESS3';Rejections_nonparametric_basis];
Aux4=[MeanPV4';QuantilesPV4';MeanGEW4';QuantilesGEW4';MedianESS4';Rejections_thetabasis];
Aux6=[MeanPV6';QuantilesPV6';MeanGEW6';QuantilesGEW6';MedianESS6';Rejections_combined_basis];


TableSummaries=[Aux0 Aux3 Aux4 Aux6];

save('DiagnosticsSummary.mat','TableSummaries','MH_AcceptanceProbabilities')



